name: Nightly Data Update

on:
  schedule:
    # Kör varje natt kl 03:00 UTC
    - cron: '0 5 * * *'
  workflow_dispatch: # Tillåter manuell körning

jobs:
  run_nightly_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Eller den version du använder
      - name: Install dependencies
        run: npm ci
      - name: Run Nightly Update
        run: node src/index.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          # Andra miljövariabler som behövs
